"""Personalización Jazzmin — CPEH Fase II ROJO (identidad portal CPEH)."""
JAZZMIN_SETTINGS = {
    "site_title": "CPEH · Habitabilidad",
    "site_header": "Seguimiento inspecciones ROJO",
    "site_brand": "Fase II · ROJO",
    "site_logo": "img/logo-cpeh-sidebar.svg",
    "site_logo_classes": "brand-image-cpeh elevation-2",
    "site_icon": "img/logo-cpeh-sidebar.svg",
    "login_logo": "img/logo-cpeh-redes.svg",
    "login_logo_dark": "img/logo-cpeh-redes.svg",
    "welcome_sign": "Comisión Presidencial para la Evaluación de Habitabilidad de Infraestructuras",
    "copyright": "Comisión Presidencial para la Evaluación de Habitabilidad de Infraestructuras",
    "search_model": ["inspecciones.CasoRojo", "auth.User"],
    "topmenu_links": [
        {"name": "Inicio", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Mapa GPS", "url": "/mapa/", "new_window": True, "permissions": ["inspecciones.view_casorojo"]},
        {"name": "Asignación", "url": "/asignacion/", "new_window": True, "permissions": ["auth.view_user"]},
        {"name": "Tutorial", "url": "/admin/#tutorial-sistema", "permissions": ["auth.view_user"]},
        {"name": "Plantilla Excel", "url": "/admin/inspecciones/casorojo/", "permissions": ["inspecciones.view_casorojo"]},
        {"name": "Health API", "url": "/api/health/", "new_window": True},
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": ["inspecciones", "auth"],
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.group": "fas fa-users",
        "inspecciones.CasoRojo": "fas fa-building",
        "inspecciones.Procedimiento": "fas fa-toolbox",
        "inspecciones.HistorialEstado": "fas fa-history",
        "inspecciones.EvidenciaFoto": "fas fa-camera",
        "inspecciones.InformePdfAdjunto": "fas fa-file-pdf",
    },
    "default_icon_parents": "fas fa-folder",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": True,
    "custom_css": "css/cpeh_admin.css",
    "show_ui_builder": False,
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "inspecciones.casorojo": "collapsible",
    },
    "language_chooser": False,
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": True,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-primary",
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": True,
    "theme": "flatly",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
}
